import { User, Store, Rating, UserRole } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    address: '123 Main St, New York',
    role: UserRole.SYSTEM_ADMIN,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    address: '456 Oak Ave, Los Angeles',
    role: UserRole.NORMAL_USER,
    createdAt: '2024-01-02',
    updatedAt: '2024-01-02',
  },
  {
    id: '3',
    name: 'Bob Wilson',
    email: 'bob@example.com',
    address: '789 Pine Rd, Chicago',
    role: UserRole.STORE_OWNER,
    createdAt: '2024-01-03',
    updatedAt: '2024-01-03',
  },
  {
    id: '4',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    address: '321 Elm St, Houston',
    role: UserRole.NORMAL_USER,
    createdAt: '2024-01-04',
    updatedAt: '2024-01-04',
  },
  {
    id: '5',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    address: '654 Maple Dr, Phoenix',
    role: UserRole.STORE_OWNER,
    createdAt: '2024-01-05',
    updatedAt: '2024-01-05',
  },
];

export const MOCK_STORES: Store[] = [
  {
    id: '1',
    storeName: 'TechHub Electronics',
    email: 'contact@techhub.com',
    address: '789 Pine Rd, Chicago',
    ownerId: '3',
    averageRating: 4.5,
    totalRatings: 24,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '2',
    storeName: 'Fashion Forward',
    email: 'info@fashionforward.com',
    address: '321 Elm St, Houston',
    ownerId: '3',
    averageRating: 4.2,
    totalRatings: 18,
    createdAt: '2024-01-02',
    updatedAt: '2024-01-02',
  },
  {
    id: '3',
    storeName: 'Quick Mart',
    email: 'support@quickmart.com',
    address: '654 Maple Dr, Phoenix',
    ownerId: '5',
    averageRating: 3.8,
    totalRatings: 32,
    createdAt: '2024-01-03',
    updatedAt: '2024-01-03',
  },
  {
    id: '4',
    storeName: 'Fresh Grocery',
    email: 'hello@freshgrocery.com',
    address: '147 Birch Ln, Philadelphia',
    ownerId: '5',
    averageRating: 4.7,
    totalRatings: 41,
    createdAt: '2024-01-04',
    updatedAt: '2024-01-04',
  },
  {
    id: '5',
    storeName: 'Book Paradise',
    email: 'books@paradise.com',
    address: '258 Cedar St, San Antonio',
    ownerId: '3',
    averageRating: 4.9,
    totalRatings: 15,
    createdAt: '2024-01-05',
    updatedAt: '2024-01-05',
  },
];

export const MOCK_RATINGS: Rating[] = [
  {
    id: '1',
    storeId: '1',
    userId: '2',
    score: 5,
    createdAt: '2024-06-01',
    updatedAt: '2024-06-01',
    userName: 'Jane Smith',
    userEmail: 'jane@example.com',
    storeName: 'TechHub Electronics',
  },
  {
    id: '2',
    storeId: '1',
    userId: '4',
    score: 4,
    createdAt: '2024-06-02',
    updatedAt: '2024-06-02',
    userName: 'Alice Johnson',
    userEmail: 'alice@example.com',
    storeName: 'TechHub Electronics',
  },
  {
    id: '3',
    storeId: '2',
    userId: '2',
    score: 4,
    createdAt: '2024-06-03',
    updatedAt: '2024-06-03',
    userName: 'Jane Smith',
    userEmail: 'jane@example.com',
    storeName: 'Fashion Forward',
  },
  {
    id: '4',
    storeId: '3',
    userId: '4',
    score: 3,
    createdAt: '2024-06-04',
    updatedAt: '2024-06-04',
    userName: 'Alice Johnson',
    userEmail: 'alice@example.com',
    storeName: 'Quick Mart',
  },
  {
    id: '5',
    storeId: '4',
    userId: '2',
    score: 5,
    createdAt: '2024-06-05',
    updatedAt: '2024-06-05',
    userName: 'Jane Smith',
    userEmail: 'jane@example.com',
    storeName: 'Fresh Grocery',
  },
];

// Mock credentials for testing
export const MOCK_CREDENTIALS = [
  { email: 'admin@example.com', password: 'Admin@123' },
  { email: 'user@example.com', password: 'User@1234' },
  { email: 'owner@example.com', password: 'Owner@123' },
];
